add soluction for home task lection 2
js-tasks-ru/htmlcss-20210114_insomnia7 pull request #3
Opened 2021-01-25 19:58 UTC by AlexeyMart

2021-01-26 00:46 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно

Добавляю преподавателя (@PDmitryA) для код-ревью, посмотрим что он скажет :)

2021-01-29 19:19 UTC, PDmitryA requested changes

2021-01-29 19:19 UTC, diarmind commented on 04-lection2/01-histogram/histogram.css
> +.chart {
если отдельным блоком, то положи рядом, пожалуйста, в `chart.css`
вообще гистограмма была задумана как один бэм-блок)

2021-01-29 19:19 UTC, diarmind commented on 04-lection2/01-histogram/histogram.css
> +  transform: scaleY(1.1) translateY(-5%);
прикольно

2021-01-29 19:19 UTC, diarmind commented on 04-lection2/02-skeleton/skeleton.css
> +но если прокомментируете и расшифруете - будет здорово :) */
здесь анимация задана через @keyframes. о них поговорим на лекции про анимацию, но раз она одна из последних, то совсем коротенько опишу, чего здесь происходит.

keyframes - ключевые кадры анимации. по ним и происходит анимирование. они именованые - у тебя названы "skeleton-loading".
внутри ты задал тайминги анимации в процентах - 0% и 100%.
для каждого "тайминга" описал желаемые к применению свойства. какие-то свойства браузеры умеют "анимировать", а какие-то нет. переместить background с одного положения на другое - вполне решаемая задача, и браузер с ней справляется. о трудоемкости прямо сейчас не говорим.

2021-01-29 19:19 UTC, diarmind commented on 05-lection3/01-tooltip/tooltip.css
> +}
надо бы вынести отсюда. потом подключим в проект файл с тултипом, и это применится ко всей страничке (главной или компонента, например). такое нужно положить либо в `<styles>` странички для демонстрации, либо в отдельный css-файл рядом.

2021-01-29 19:19 UTC, PDmitryA commented on assets/css/variables.css
> +  --color-background-white: #ffffff;
в названиях css-переменных явно указаны цвета (white, black, gray), но если они поменяются для другой темы, то перестанут соответствовать их значениям.
давай уйдем от такого нейминга?

2021-01-29 19:19 UTC, PDmitryA commented on components/page/page.css
> +.main-page__card:nth-child(3n) {
окей, имеет право на жизнь

2021-01-29 19:19 UTC, PDmitryA commented on components/page/page.css
> +  --margin-card: 30px;
определенно хорошо, что есть некоторое значение, относительно которого меняется блок. не нужно злоупотреблять переменными, но здесь уместно.

зачем эта переменная на уровне всего html-документа? почему не бэм-блока? подразумевается, что она может поменяться?

2021-01-29 19:19 UTC, PDmitryA commented on 05-lection3/01-tooltip/tooltip.css
> +  /* // чтобы не было пропадания cursor pointer из-за перекрытия псевдоэлементом */
странный синтаксис комментария
в css не поддерживаются комментарии через `//`, но как ни странно из-за механизма обработки правил, браузеры просто посчитают, что они "не поняли" свойство с именем `//` и все равно не сломаются.

конечно, правильно писать `/* комментарий */`

2021-01-29 19:19 UTC, PDmitryA commented on 04-lection2/02-skeleton/skeleton.css
> +но если прокомментируете и расшифруете - будет здорово :) */
можешь применить
`background-position: 100% 50%;` - посмотреть на то, как выглядит
`background-position: 0 50%;` - посмотреть, как выглядит
и от 0% до 100% <s>линейно интерполировать</s> подвигать значение в девтулзах. просто поставь курсор в режим редактирования и нажми стрелочку вверх на клавиатуре. вот магия и закончилась)

2021-02-25 22:11 UTC, PDmitryA approved these changes

2021-02-25 22:11 UTC, PDmitryA commented on 04-lection2/01-histogram/chart.css
> +.chart__item:nth-child(5n + 1) {
для демонстрации это ок
вообще в данном примере подразумевалось, что высота будет задана inline-стилем

2021-02-25 22:11 UTC, jsru commented
К сожалению, PR не может быть замержен, PDmitryA вероятно сможет помочь.

2021-02-25 22:14 UTC, PDmitryA commented
если смержишь с добавленными задачами, то в чистовик перенесем.

p.s. перенос в чистовик вообще говоря ни на что не влияет.
те задачки, что есть в pr можешь считать принятыми, а в сертификате все равно не пишется, сколько решено.

так что если лень - можно просто закрыть pr)

спасибо тебе за активность на лекциях!

2021-02-26 06:31 UTC, AlexeyMart commented
> если смержишь с добавленными задачами, то в чистовик перенесем.
> 
> p.s. перенос в чистовик вообще говоря ни на что не влияет.
> те задачки, что есть в pr можешь считать принятыми, а в сертификате все равно не пишется, сколько решено.
> 
> так что если лень - можно просто закрыть pr)
> 
> спасибо тебе за активность на лекциях!

Дмитрий, Вам большое спасибо за курс! было классно!!!

2021-02-26 06:31 UTC, closed without merging